
post:
    path:     /post
    defaults: { _controller: "bluehouseapp.controller.post:listAction" }
    requirements: { _method: get }
post_by_node:
    path:     /post/node/{currentNodeId}
    defaults:
      _controller: bluehouseapp.controller.post:listPostsByNodeAction
      _bluehouseapp:
        template:  BluehouseappWebBundle:Frontend/Post:postsByNode.html.twig
        paginate: 20

post_by_category:
    path:     /post/category/{currentCategoryId}
    defaults:
      _controller: bluehouseapp.controller.post:listPostsByCategoryAction
      _bluehouseapp:
        template:  BluehouseappWebBundle:Frontend/Post:index.html.twig
        paginate: 20

post_create:
        path:     /member/post/{nodeId}
        defaults: { _controller: "bluehouseapp.controller.post:createPostAction" }
        requirements: { _method: get|post }
post_new:
        path:    /member/post/new/{nodeId}
        defaults: { _controller: "bluehouseapp.controller.post:newPostAction" }
        requirements: { _method: get|post }
post_show:
        path:    /post/{id}
        defaults: { _controller: "bluehouseapp.controller.post:showPostAction" }
        requirements: { _method: get|post }
post_comment_create:
        path:    /member/post/comment/update/{id}
        defaults: { _controller: "bluehouseapp.controller.post:commentCreateAction" }
        requirements: { _method: get|post }
member_needAvatarImage:
        path:    /member/needAvatarImage
        defaults:
           _controller: bluehouseapp.controller.member:needAvatarImageAction
           _bluehouseapp:
             template:  BluehouseappWebBundle:Frontend/Member:needAvatarImage.html.twig
member_edit:
        path:    /member/edit
        defaults:
           _controller: bluehouseapp.controller.member:editMemberAction
           _bluehouseapp:
             template:  BluehouseappWebBundle:Frontend/Member:edit.html.twig
member_update_image:
        path:   /member/updateImage
        defaults:
           _controller: bluehouseapp.controller.member:updateMemberImageAction
           _bluehouseapp:
             template:  BluehouseappWebBundle:Frontend/Member:edit.html.twig
member_update:
        path:    /member/update
        defaults:
           _controller: bluehouseapp.controller.member:updateMemberAction
           _bluehouseapp:
             template:  BluehouseappWebBundle:Frontend/Member:edit.html.twig
user_show:
        path:    /user/{username}
        defaults:
           _controller: bluehouseapp.controller.member:showMemberAction
           _bluehouseapp:
             template:  BluehouseappWebBundle:Frontend/Member:show.html.twig
user_show_topics:
        path:    /user/{username}/topics
        defaults:
           _controller: bluehouseapp.controller.member:showMemberTopicsAction
           _bluehouseapp:
             template:  BluehouseappWebBundle:Frontend/Member:showTopics.html.twig
user_show_replies:
        path:    /user/{username}/replies
        defaults:
           _controller: bluehouseapp.controller.member:showMemberRepliesAction
           _bluehouseapp:
             template:  BluehouseappWebBundle:Frontend/Member:showReplies.html.twig


