#==============H!Grid CMS设置      自定义变量

# 在模板中使用网站访问地址。网页链接的根部URL，不带后斜杠/
_higrid_root_url: http://my.higrid.net

# 作者名称
_higrid_author_name: <a target="_top" href="http://higrid.net/">嗨网在线</a>

# 在rss中显示
_higrid_email: higrid@qq.com   # 邮箱地址
site_desc: 这是我的博客 # 描述


##博客在_content中的文件夹名称，在模板中使用
blog_name: blog

#==============H!Grid CMS设置    系统变量

# 如果在子目录中使用请更改，如/hi/
_site_root: /

# 站点名称
_site_name: 嗨网博客

# 内容文件夹，此处更改请更改对应内容文件夹
_content_root: _content

# 作为永久链接使用
_site_url: http://higrid.net

# 模板风格文件夹
_theme: higridcms

# 帖子时间戳
_entry_timestamps: false

# 日期格式
_date_format: 'Y-M-D'

# 时区
_timezone: Asia/Shanghai

# taxonomy设置
_taxonomy:
  - category
  - tags

# 保持默认
_taxonomy_slugify: false

# 大小写敏感，保持默认
_taxonomy_case_sensitive: false

# 强制转换小写，保持默认
_taxonomy_force_lowercase: true

# 选择内容格式，默认markdown，可选择
#  - markdown
#  - markdown_edge (extra, markdown扩展)
#  - textile
#  - html
#  - txt
_content_type: markdown