# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2013-2014
  project: '(FS) Media Gallery'
  version: 1.0.0
  release: 1.0.0
  latex_documents:
  - - Index
    - fs_media_gallery.tex
    - '(FS) Media Gallery: A FAL based media gallery for TYPO3'
    - Frans Saris
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
...
