# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.


---
conf.py:
  copyright: 2012-2019
  project: Dynamic Content Elements (DCE)
  version: 2.3
  release: 2.3.1
  latex_documents:
  - - Index
    - dce.tex
    - 'Dynamic Content Elements (DCE)'
    - Armin Vieweg
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3api:
    - http://docs.typo3.org/typo3cms/CoreApiReference/
    - null
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3start:
    - http://docs.typo3.org/typo3cms/GettingStartedTutorial/
    - null
    t3editors:
    - http://docs.typo3.org/typo3cms/EditorsTutorial/
    - null
...
