# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

# Below is an example of intersphinx mapping declaration
# Add more mappings depending on what manual you want to link to
# Remove entirely if you don't need cross-linking

---
conf.py:
  copyright: 2018
  project: 应用案例
  version: 1.0.0
  release: 1.0.0
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
  latex_documents:
  - - Index
    - case_tab.tex
    - 应用案例
    - 杨世昌
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Example-ExtensionManual
    github_branch: latest
...
