imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'BluehouseappWebBundle:common:form_theme.html.twig'
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

trsteel_ckeditor:
    class: Trsteel\CkeditorBundle\Form\Type\CkeditorType
    transformers: ['html_purifier']
    toolbar: ['document', 'clipboard', 'editing', '/', 'basicstyles', 'paragraph', 'links', '/', 'insert', 'styles', 'tools']
    toolbar_groups:
        document: ['Source','-','Save','-','Templates']
        clipboard: ['Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo']
        editing: ['Find','Replace','-','SelectAll']
        basicstyles: ['Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat']
        paragraph: ['NumberedList','BulletedList','-','Outdent','Indent','-','JustifyLeft', 'JustifyCenter','JustifyRight','JustifyBlock']
        links: ['Link','Unlink','Anchor']
        insert: ['Image','Flash','Table','HorizontalRule']
        styles: ['Styles','Format']
        tools: ['Maximize', 'ShowBlocks']
    ui_color: '#000000'
    startup_outline_blocks: true
    width: 100% #Integer or %
    height: 400 #Integer or %
    language: 'zh-cn'

fm_elfinder:
    locale: %locale% # defaults to current request locale
    editor: ckeditor # other choices are tinymce or simple
    #showhidden: false
    fullscreen: true # defaults true, applies to simple and ckeditor editors
    include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
    compression: false # enable if you configured the uglifycss and uglifyjs2 assetic filters and want compression
    connector:
        debug: false # defaults to false
        roots:       # at least one root must be defined
            uploads:
                driver: LocalFileSystem
                path: assets/uploads
                upload_allow: ['image/png', 'image/jpg', 'image/jpeg','image/gif']
                upload_deny: ['all']
                upload_max_size: 4M


knp_time: ~

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Bluehouseapp\Bundle\CoreBundle\Entity\Member
    from_email:
        address:        %mailer_user%
        sender_name:   蓝房子

#fos_rest:
#   format_listener:
#            rules:
#            - { path: '^/', priorities: [ 'json', 'html'], fallback_format: html, prefer_extension: true }
#   view:
#        formats:
#            json: true
#   disable_csrf_role: ROLE_ADMIN

fos_rest:
    disable_csrf_role: ROLE_API
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204
    format_listener:
        rules:
             - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
             - { path: '^/' }

liip_imagine:
    filter_sets:
        face_image:
            quality: 100
            filters:
                thumbnail: { size: [170, 170], mode: outbound}
        avatar_image:
            quality: 100
            filters:
                thumbnail: { size: [73, 73], mode: outbound }
        banner_image:
            quality: 100
            filters:
                thumbnail: { size: [940, 360], mode: outbound }
        small_image:
            quality: 100
            filters:
                thumbnail: { size: [48, 48], mode: outbound }
        mini_image:
            quality: 100
            filters:
                thumbnail: { size: [36, 36], mode: outbound }
        product_image:
                     quality: 100
                     filters:
                         thumbnail: { size: [480, 480], mode: outbound }
        page_image:
            quality: 100
            filters:
                relative_resize: { widen: 600 }
        app_mini_image:
            quality: 100
            filters:
                bluehouseapp_filter: { max: [36, 36], mode: outbound }
        app_avatar_image:
            quality: 100
            filters:
                bluehouseapp_filter: { max: [73, 73], mode: outbound }
knp_gaufrette:
    stream_wrapper: ~
    adapters:
        image_adapter:
            local:
                directory: %kernel.root_dir%/../web/assets/images
        avatar_adapter:
            local:
                directory: %kernel.root_dir%/../web/assets/avatar
        party_adapter:
            local:
                directory: %kernel.root_dir%/../web/assets/party
        node_adapter:
            local:
                directory: %kernel.root_dir%/../web/assets/node
        discuss_adapter:
            local:
                directory: %kernel.root_dir%/../web/assets/discuss
        member_adapter:
            local:
                directory: %kernel.root_dir%/../web/assets/member
    filesystems:
        image_fs:
            adapter:    image_adapter
        avatar_fs:
            adapter:    avatar_adapter
        party_fs:
            adapter:    party_adapter
        node_fs:
            adapter:    node_adapter
        discuss_fs:
            adapter:    discuss_adapter
        member_fs:
            adapter:    member_adapter

vich_uploader:
    db_driver: orm
    twig: true
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        image_image:
            namer: vich_uploader.namer_uniqid
            uri_prefix: /assets/images
            upload_destination: image_fs
            delete_on_remove: true
            inject_on_load: true
        avatar_image:
            namer: vich_uploader.namer_uniqid
            uri_prefix: /assets/avatar
            upload_destination: avatar_fs
            delete_on_remove: true
            inject_on_load: true
        party_image:
            namer: vich_uploader.namer_uniqid
            uri_prefix: /assets/party
            upload_destination: party_fs
            delete_on_remove: true
            inject_on_load: true
        node_image:
            namer: vich_uploader.namer_uniqid
            uri_prefix: /assets/node
            upload_destination: node_fs
            delete_on_remove: true
            inject_on_load: true
        discuss_image:
            namer: vich_uploader.namer_uniqid
            uri_prefix: /assets/discuss
            upload_destination: discuss_fs
            delete_on_remove: true
            inject_on_load: true
        memeber_image:
            namer: vich_uploader.namer_uniqid
            uri_prefix: /assets/member
            upload_destination: member_fs
            delete_on_remove: true
            inject_on_load: true


monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console

fos_oauth_server:
      db_driver: orm       # Driver availables: orm, mongodb, or propel
      client_class:  Bluehouseapp\Bundle\CoreBundle\Entity\Client
      access_token_class: Bluehouseapp\Bundle\CoreBundle\Entity\AccessToken
      refresh_token_class: Bluehouseapp\Bundle\CoreBundle\Entity\RefreshToken
      auth_code_class:  Bluehouseapp\Bundle\CoreBundle\Entity\AuthCode
      service:
           user_provider: fos_user.user_manager

jms_serializer:
    metadata:
        cache: file
        debug: true
        #debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        auto_detection: true
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/Resources/FOSUserBundle/serializer"
            bluehouseapp-post:
                namespace_prefix: "Bluehouseapp\\Bundle\\CoreBundle"
                path: "@BluehouseappCoreBundle/Resources/config/serializer"
